name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run sshpass commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ~/htdocs/e-commerce.dev-laravel.co
          git pull
          composer install
          echo "yes" | php artisan migrate
          php artisan config:clear
          php artisan view:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:cache
          php artisan route:cache
          php artisan config:cache



