name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: create-directory
      uses: nekiro/ssh-job@main
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        user: ${{ secrets.USER }}
        command: |
          cd /home/cloudpanel/htdocs/e-commerce.dev-laravel.co
          git pull
          php8.1 /usr/local/bin/composer install
          echo "yes" | php8.1 artisan migrate
          php8.1 artisan config:cache
          php8.1 artisan view:cache
          php8.1 artisan route:cache
          php8.1 artisan config:cache







